# Generated by Django 5.1.7 on 2025-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('Kids', 'Kids'), ('Women', 'Women'), ('Men', 'Men')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
