# Generated by Django 5.1.7 on 2025-04-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created',
        ),
    ]
