# Generated by Django 5.1.7 on 2025-11-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_productimage_options_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Upload product image', upload_to='', verbose_name='image'),
        ),
    ]
